pipeline {

  agent any
  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 30, unit: 'MINUTES')
  }

  environment {
    GITHUB_ACTOR = credentials('MARKETPLACE_GITHUB_OWNER')
    GITHUB_REPOSITORY_OWNER = 'axonivy-market'
    UI_IMAGE_NAME = 'marketplace-ui'
    APP_IMAGE_NAME = 'marketplace-app'
    STABLE_IMAGE_NAME = 'marketplace-stable'
    MARKETPLACE_GIT_URL = credentials('MARKETPLACE_GIT_URL')
    GH_TOKEN = credentials('GH_TOKEN')
    VERSION_RETENTION_COUNT = credentials('VERSION_RETENTION_COUNT')
    OCTOPUS_MAIL = credentials('OCTOPUS_MAIL')
    OCTOPUS_ACCOUNT_NAME = credentials('OCTOPUS_ACCOUNT_NAME')
    MARKETPLACE_ENV_FILE = credentials('MARKETPLACE_PROD_ENV_FILE')
  }

  parameters {
    gitParameter(
      name: 'BRANCH',
      type: 'PT_BRANCH',
      defaultValue: 'origin/develop',
      description: 'Choose your GitHub branch',
      branchFilter: '.*',
      tagFilter: '*',
      sortMode: 'NONE',
      selectedValue: 'DEFAULT',
      quickFilterEnabled: true
    )
    string(name: 'RELEASE_VERSION', defaultValue: 'latest', description: 'Release version')
  }

  stages {

    stage('Set Display Name') {
      steps {
        script {
          def userId = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0]?.userId
          def fullName = "system"
          if (userId) {
            def user = jenkins.model.Jenkins.instance.getUser(userId)
            fullName = user?.getDisplayName() ?: userId
          }
          currentBuild.displayName = "Build #${env.BUILD_NUMBER} on branch ${BRANCH} with release version of ${RELEASE_VERSION} - trigger by ${fullName}"
        }
      }
    }
    
    stage('Checkout Source') {
      steps {
        script {
          def gitBranch = params.BRANCH.replaceFirst(/^origin\//, '')
          sh 'rm -rf target-source'
          dir('target-source') {
            git branch: gitBranch, url: env.MARKETPLACE_GIT_URL
          }
        }
      }
    }

    stage('Stop running docker container for compose file') {
      steps {
        script {
          try {
            sh 'docker compose --project-name marketplace -f ./target-source/marketplace-build/templates/docker-compose.yml down --rmi all'
          } catch (Exception e) {
            echo "Error during docker compose down, continuing: ${e}"
          }
        }
      }
    }

    stage('Update Version and Tag Source') {
      steps {
        dir('target-source') {
          withEnv([
            "CORE_POM_FILE=./marketplace-service/core/pom.xml",
            "APP_POM_FILE=./marketplace-service/app/pom.xml",
            "STABLE_POM_FILE=./marketplace-service/stable/pom.xml",
            "PACKAGE_FILE=./marketplace-ui/package.json"
          ]) {
            script {
              sh '''
                mvn versions:set -DnewVersion=$RELEASE_VERSION -f  $CORE_POM_FILE
                mvn versions:set -DnewVersion=$RELEASE_VERSION -f  $APP_POM_FILE
                mvn versions:set -DnewVersion=$RELEASE_VERSION -f  $STABLE_POM_FILE
                sed -i 's/"version": \"[^\"]*\"/"version": "$RELEASE_VERSION"/' $PACKAGE_FILE
                git config --global user.email $OCTOPUS_MAIL
                git config --global user.name $OCTOPUS_ACCOUNT_NAME
                git remote set-url origin https://$GITHUB_ACTOR:$GH_TOKEN@github.com/axonivy-market/marketplace.git
                git push --delete origin $RELEASE_VERSION || true
                git tag -d $RELEASE_VERSION || true
                git commit -a -m "Update version to $RELEASE_VERSION"
                git tag $RELEASE_VERSION
                git push origin $RELEASE_VERSION
              '''
            }
          }
        }
      }
    }

    stage('Build env file') {
      steps {
        sh '''
          ENV_FILE='./target-source/marketplace-build/templates/.env'
          cp "$MARKETPLACE_ENV_FILE" "$ENV_FILE"

          if grep -q '^RELEASE_VERSION=' "$ENV_FILE"; then
            sed -i "s|^RELEASE_VERSION=.*$|RELEASE_VERSION=$RELEASE_VERSION|" "$ENV_FILE"
          else
            echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$ENV_FILE"
          fi

          chmod 600 "$ENV_FILE"
        '''
      }
    }

    stage('Build Docker Images') {
      steps {
        script {
          dir("./target-source/marketplace-build/templates/dev") {
            sh '''
                export NGINX_CONFIG_PATH=../../nginx/nginx.conf
                export BUILD_ENV=production
                export BUILD_VERSION=$RELEASE_VERSION
                export NGINX_PORT=80
                docker compose --project-name marketplace up --build
                docker compose --project-name marketplace up --force-recreate -d
            '''
          }
        }
      }
    }

    stage('Wait for Containers') {
      steps {
        dir('./target-source/marketplace-build/templates') {
          sh '''
            timeout=300
            start_time=$(date +%s)
            while [ $(($(date +%s) - start_time)) -lt $timeout ]; do
              if docker compose --project-name marketplace ps | grep -q "Up"; then
                echo "Containers are up and running."
                exit 0
              fi
              echo "Waiting for containers to start..."
              sleep 5
            done
            echo "Containers did not start within the timeout period."
            exit 1
          '''
        }
      }
    }

    stage('Log in to GitHub Container Registry') {
      steps {
        sh """
          echo $GH_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        """
      }
    }

    stage('Release Marketplace UI Image') {
      steps {
        sh '''
          # Prepare UI image
          UI_IMAGE_ID=ghcr.io/$GITHUB_REPOSITORY_OWNER/$UI_IMAGE_NAME
          docker tag $UI_IMAGE_ID:latest $UI_IMAGE_ID:$RELEASE_VERSION
          docker push $UI_IMAGE_ID:$RELEASE_VERSION
          # Cleanup old UI image versions
          export IMAGE_NAME=$UI_IMAGE_NAME
          bash ./.build/scripts/ghcr-cleanup.sh
        '''
      }
    }

    stage('Release Marketplace App Image') {
      steps {
        sh '''
          # Prepare App image
          APP_IMAGE_ID=ghcr.io/$GITHUB_REPOSITORY_OWNER/$APP_IMAGE_NAME
          docker tag $APP_IMAGE_ID:latest $APP_IMAGE_ID:$RELEASE_VERSION
          docker push $APP_IMAGE_ID:$RELEASE_VERSION
          # Cleanup old App image versions
          export IMAGE_NAME=$APP_IMAGE_NAME
          bash ./.build/scripts/ghcr-cleanup.sh
        '''
      }
    }

    stage('Release Marketplace Stable Image') {
      steps {
        sh '''
          # Prepare Stable image
          STABLE_IMAGE_ID=ghcr.io/$GITHUB_REPOSITORY_OWNER/$STABLE_IMAGE_NAME
          docker tag $STABLE_IMAGE_ID:latest $STABLE_IMAGE_ID:$RELEASE_VERSION
          docker push $STABLE_IMAGE_ID:$RELEASE_VERSION
          # Cleanup old Stable image versions
          export IMAGE_NAME=$STABLE_IMAGE_NAME
          bash ./.build/scripts/ghcr-cleanup.sh
        '''
      }
    }
  }
}
