# Used for the local environment
name: marketplace

services:
  ui:
    env_file:
      - ../.env
      - dev.env
    build:
      context: ../../../marketplace-ui
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV}
    volumes:
      - marketbrowser:/browser_share
    restart: always
    command: sh -c "cp -r /app/dist/browser/* /browser_share && node dist/server/server.mjs"
    expose:
      - 4000
    networks:
      - marketplace-network

  app:
    restart: always
    volumes:
      - marketcache:/app/data/market-cache
      - ${APP_LOG_PATH}:/app/logs
    env_file:
      - ../.env
      - dev.env
    build:
      context: ../../../marketplace-service
      dockerfile: app/Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION}
    expose:
      - 8080
    networks:
      - marketplace-network

  stable:
    restart: always
    volumes:
      - ${STABLE_LOG_PATH}:/app/logs
    env_file:
      - ../.env
      - dev.env
    build:
      context: ../../../marketplace-service
      dockerfile: stable/Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION}
    expose:
      - 8085
    networks:
      - marketplace-network

networks:
  marketplace-network:
    external: true

volumes:
  marketcache:
    name: marketplace_marketcache
    external: true
  marketbrowser:
    name: marketplace_marketbrowser
    external: true
