# Used for the local environment
name: marketplace

services:
  nginx:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
      - marketcache:/usr/share/nginx/html/market-cache
      - marketbrowser:/usr/share/nginx/html/browser
    ports:
      - "4500:80"
    depends_on:
      - ui
      - app
    networks:
      - marketplace-network

  ui:
    env_file:
      - ../.env
    build:
      context: ../../../marketplace-ui
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV}
    volumes:
      - marketbrowser:/browser_share
    restart: always
    command: sh -c "cp -r /app/dist/browser/* /browser_share && node dist/server/server.mjs"
    expose:
      - 4000
    networks:
      - marketplace-network

  app:
    restart: always
    volumes:
      - /home/axonivy/marketplace/data/market-installations.json:/app/data/market-installation.json
      - marketcache:/app/data/market-cache
      - ../logs:/app/logs
    env_file:
      - ../.env
    build:
      context: ../../../marketplace-service
      dockerfile: app/Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION}
    expose:
      - 8080
    networks:
      - marketplace-network

  stable:
    restart: always
    volumes:
      - ../logs/stable:/app/logs
    env_file:
      - ../.env
    build:
      context: ../../../marketplace-service
      dockerfile: stable/Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION}
    expose:
      - "8080"
    networks:
      - marketplace-network

networks:
  marketplace-network:
    external: true

volumes:
  marketcache:
  marketbrowser:
