name: marketplace

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    container_name: mongodb-7.0.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
      - ./config/mongodb/mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]

  marketplace-ui:
    build:
      context: .
      additional_contexts:
        assets: ../marketplace-ui/dist/
      dockerfile: Dockerfile-UI
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "85:80"

  marketplace-service:
    image: marketplace-service
    container_name: marketplace-service
    restart: always
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_DATABASE=marketplace
      - MONGODB_USERNAME=${SERVICE_MONGODB_USER}
      - MONGODB_PASSWORD=${SERVICE_MONGODB_PASSWORD}
    build:
      context: .
      additional_contexts:
        assets: ../marketplace-service/target/
      dockerfile: Dockerfile-Service
    volumes:
      - ../marketplace-service/target/marketplace-service-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/marketplace-service.war
    ports:
      - "8080:8080"

volumes:
  mongodata: