name: marketplace

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    container_name: marketplace-mongodb-7.0.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
      - ./config/mongodb/mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]

  ui:
    container_name: marketplace-ui
    build:
      context: ../marketplace-ui
      additional_contexts:
        assets: ../marketplace-build/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "90:80"
    depends_on:
      - service

  service:
    container_name: marketplace-service
    restart: always
    environment:
      - MONGODB_HOST=${SERVICE_MONGODB_HOST}
      - MONGODB_DATABASE=${SERVICE_MONGODB_DATABASE}
      - MONGODB_USERNAME=${SERVICE_MONGODB_USER}
      - MONGODB_PASSWORD=${SERVICE_MONGODB_PASSWORD}
      - MARKET_GITHUB_TOKEN=${MARKET_GITHUB_TOKEN}
    build:
      context: ../marketplace-service
      dockerfile: Dockerfile
    volumes:
      - ../marketplace-service/target/marketplace-service-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/marketplace-service.war
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodata: