name: marketplace

services:
  mongodb:
    container_name: marketplace-mongodb
    build:
      context: ./config/mongodb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
      - ./config/mongodb/mongod.conf:/etc/mongod.conf

  ui:
    container_name: marketplace-ui
    build:
      context: ../marketplace-ui
      additional_contexts:
        assets: ../marketplace-build/
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV}
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4200:80"
    depends_on:
      - service

  service:
    container_name: marketplace-service
    restart: always
    volumes:
      - /home/axonivy/marketplace/data/market-installations.json:/data/market-installation.json
    environment:
      - MONGODB_HOST=${SERVICE_MONGODB_HOST}
      - MONGODB_DATABASE=${SERVICE_MONGODB_DATABASE}
      - MONGODB_USERNAME=${SERVICE_MONGODB_USER}
      - MONGODB_PASSWORD=${SERVICE_MONGODB_PASSWORD}
      - MARKET_GITHUB_MARKET_BRANCH=${MARKET_GITHUB_MARKET_BRANCH}
      - MARKET_GITHUB_TOKEN=${MARKET_GITHUB_TOKEN}
      - MARKET_GITHUB_OAUTH_APP_CLIENT_ID=${MARKET_GITHUB_OAUTH_APP_CLIENT_ID}
      - MARKET_GITHUB_OAUTH_APP_CLIENT_SECRET=${MARKET_GITHUB_OAUTH_APP_CLIENT_SECRET}
      - MARKET_JWT_SECRET_KEY=${MARKET_JWT_SECRET_KEY}
      - MARKET_CORS_ALLOWED_ORIGIN=${MARKET_CORS_ALLOWED_ORIGIN}
      - MARKET_MONGO_LOG_LEVEL=${MARKET_MONGO_LOG_LEVEL}
    build:
      context: ../marketplace-service
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodata:
