# use the latest version of the official nginx image as the base image
FROM nginx:latest
# copy the custom nginx configuration file to the container in the
# default location
COPY ./config/nginx/nginx.conf /etc/nginx/nginx.conf
# copy the built Angular app files to the default nginx html directory
#COPY /dist/browser /usr/share/nginx/html
COPY --from=assets browser /usr/share/nginx/html

# the paths are relative from the Docker file
