# Use the official Tomcat 10.1 image from the Docker Hub
FROM tomcat:10.1-jdk17-openjdk-slim
# Stage 2: Run the application
#FROM openjdk:17-jdk-slim

# Set the working directory
#WORKDIR /app

# Copy the built jar file from the previous stage
#COPY --from=build /app/target/your-spring-boot-app.jar /app/app.jar
#COPY --from=assets marketplace-service-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose port 8080
#EXPOSE 8080

# Start the application
#CMD ["java", "-jar", "app.jar"]

# Remove the default ROOT webapp to avoid conflicts
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy the WAR file to the webapps directory in Tomcat
COPY --from=assets marketplace-service-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/marketplace-service.war

# Expose port 8080
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]

