package com.axonivy.market.repository;

import com.axonivy.market.core.repository.CoreCustomProductDesignerInstallationRepository;

public interface CustomProductDesignerInstallationRepository extends CoreCustomProductDesignerInstallationRepository {
}
