server:
  port: '8081'
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: '${SESSION_COOKIE_SECURE}'
  tomcat:
    connection-timeout: 240000ms
    threads:
      max: '200'
    max-swallow-size: '-1'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: '${POSTGRES_HOST_URL}'
    username: '${POSTGRES_USERNAME}'
    password: '${POSTGRES_PASSWORD}'
  jpa:
    show-sql: '${SHOW_SQL}'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html