package com.axonivy.market.repository.impl;

import com.axonivy.market.core.repository.impl.CoreCustomProductDesignerInstallationRepositoryImpl;
import com.axonivy.market.repository.CustomProductDesignerInstallationRepository;

public class CustomProductDesignerInstallationRepositoryImpl extends CoreCustomProductDesignerInstallationRepositoryImpl
    implements CustomProductDesignerInstallationRepository {
}
