package com.axonivy.market.core.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * <p>
 * Error code enumeration defining system error codes with standardized format (cseo-0000).
 * Format: c=controller, s=service, e=entity, o=other, 0000=code number.
 * </p>
 *
 * @since 15/04/2026
 * @author nqhoan
 */
@Getter
@AllArgsConstructor
@NoArgsConstructor
public enum ErrorCode {
  SUCCESSFUL("0000", "SUCCESSFUL"), PRODUCT_FILTER_INVALID("1101", "PRODUCT_FILTER_INVALID"),
  PRODUCT_SORT_INVALID("1102", "PRODUCT_SORT_INVALID"), PRODUCT_NOT_FOUND("1103", "PRODUCT_NOT_FOUND"),
  GH_FILE_STATUS_INVALID("0201", "GIT_HUB_FILE_STATUS_INVALID"), USER_NOT_FOUND("2103", "USER_NOT_FOUND"),
  GITHUB_USER_NOT_FOUND("2204", "GITHUB_USER_NOT_FOUND"), GITHUB_USER_UNAUTHORIZED("2205", "GITHUB_USER_UNAUTHORIZED"),
  FEEDBACK_NOT_FOUND("3103", "FEEDBACK_NOT_FOUND"), NO_FEEDBACK_OF_USER_FOR_PRODUCT("3103",
      "NO_FEEDBACK_OF_USER_FOR_PRODUCT"), ARGUMENT_BAD_REQUEST("4000", "ARGUMENT_BAD_REQUEST"),
  MAVEN_VERSION_SYNC_FAILED("1104", "PRODUCT_MAVEN_SYNCED_FAILED"), FEEDBACK_SORT_INVALID("3102",
      "FEEDBACK_SORT_INVALID"), INTERNAL_EXCEPTION("5000", "INTERNAL_EXCEPTION"),
  GITHUB_REPOSITORY_NOT_FOUND("0202", "GITHUB_REPOSITORY_NOT_FOUND"), NOTHING_TO_SYNC("1105", "NOTHING_TO_SYNC"),
  FILE_PROCESSING_ERROR("6001", "FILE_PROCESSING_ERROR"), INVALID_PATH("6002", "INVALID_PATH"), ARTIFACT_NOT_FOUND(
      "1106", "ARTIFACT_NOT_FOUND"), INVALID_VERSION("1107", "INVALID_VERSION"),
  TASK_ALREADY_IN_PROGRESS("1108", "TASK_ALREADY_IN_PROGRESS"),
  RELEASE_LETTER_NOT_FOUND("1109", "RELEASE_LETTER_NOT_FOUND"), RELEASE_LETTER_RELEASE_VERSION_ALREADY_EXISTED("1110",
      "RELEASE_LETTER_OF_THIS_VERSION_ALREADY_EXISTED"), SPRINT_CANNOT_BE_BLANK("1111",
      "SPRINT_CANNOT_BE_BLANK"), VERSION_NOT_FOUND("3103", "VERSION_NOT_FOUND"),
  ARCHIVE_NOT_ALLOWED("1112", "ARCHIVE_NOT_ALLOWED"),
  UNARCHIVE_FAILED("1113", "UNARCHIVE_FAILED");

  private String code;
  private String helpText;
}
