services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    container_name: mongodb-7.0.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=
      - MONGODB_INITDB_ROOT_PASSWORD=
      - ./mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]
    
volumes:
  mongodata: