# This docker compose to init mongo for setup auth
name: marketplace

services:
  mongodb:
    container_name: marketplace-mongodb-non-authen
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    
volumes:
  mongodata:
