name: marketplace-website

services:
  mongodb:
    container_name: marketplace-mongodb-7.0.0
    build:
      context: ../config/mongodb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
      - ../config/mongodb/mongod.conf:/etc/mongod.conf

  ui:
    image: ghcr.io/nqhoan-axonivy/marketplace/marketplace-nginx:latest

  service:
    image: ghcr.io/nqhoan-axonivy/marketplace/marketplace-service:latest

volumes:
  mongodata: