name: marketplace-website

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    container_name: marketplace-mongodb-7.0.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
      - ../config/mongodb/mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]

  nginx:
    image: ghcr.io/nqhoan-axonivy/marketplace/marketplace-nginx:latest

  marketplace-service:
    image: ghcr.io/nqhoan-axonivy/marketplace/marketplace-service:latest

volumes:
  mongodata: