name: marketplace

services:
  mongodb:
    container_name: marketplace-mongodb-7.0.0
    build:
      context: ../config/mongodb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
      - ../config/mongodb/mongod.conf:/etc/mongod.conf

  ui:
    image: ghcr.io/axonivy-market/marketplace-ui:sprint
    restart: always
    ports:
      - "95:80"

  service:
    image: ghcr.io/axonivy-market/marketplace-service:sprint
    restart: always
    environment:
      - MONGODB_HOST=${SERVICE_MONGODB_HOST}
      - MONGODB_DATABASE=${SERVICE_MONGODB_DATABASE}
      - MONGODB_USERNAME=${SERVICE_MONGODB_USER}
      - MONGODB_PASSWORD=${SERVICE_MONGODB_PASSWORD}
      - MARKET_GITHUB_TOKEN=${MARKET_GITHUB_TOKEN}
volumes:
  mongodata:
    