pipeline {
  agent any
  options {
    ansiColor('xterm')
  }
  environment {
    UI_DIR = 'marketplace-ui'
    SONAR_PROJECT_KEY = credentials('SONAR_MARKETPLACE_UI_PROJECT_KEY')
    SONAR_PROJECT_NAME = credentials('SONAR_MARKETPLACE_UI_PROJECT_NAME')
    MARKETPLACE_GIT_URL = credentials('MARKETPLACE_GIT_URL')
  }

  stages {

    stage('Set Display Name') {
      steps {
        script {
          def userId = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0]?.userId
          def fullName = "system"
          if (userId) {
            def user = jenkins.model.Jenkins.instance.getUser(userId)
            fullName = user?.getDisplayName() ?: userId
          }
          currentBuild.displayName = "Build #${env.BUILD_NUMBER} - trigger by ${fullName}"
        }
      }
    }
    
    stage('Clone Repository') {
      steps {
        script {
          def gitBranch = params.BRANCH.replaceFirst(/^origin\//, '')
          git branch: gitBranch, url: env.MARKETPLACE_GIT_URL
        }
      }
    }

    stage('Build And Test Project') {
      steps {
        sh 'npm i --prefix ./marketplace-ui'
        sh 'npm run build --prefix ./marketplace-ui'
        sh 'rm -rf ./marketplace-ui/dist/server ./marketplace-ui/.angular/cache'
        sh 'npm run test --prefix ./marketplace-ui'
      }
    }

    stage('Docker Cleanup') {
      steps {
        sh 'docker image prune -af'
      }
    }

    stage('SonarQube Analysis') {
      steps {
        withSonarQubeEnv('Sonar') {
          dir(UI_DIR) {
            script {
              def gitBranch = params.BRANCH.replaceFirst(/^origin\//, '')
              def sonarArgs = "-Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.projectName=\"${SONAR_PROJECT_NAME}\""

              if (env.CHANGE_ID && env.CHANGE_BRANCH && env.CHANGE_TARGET) {
                sonarArgs += " -Dsonar.pullrequest.key=${env.CHANGE_ID}"
                sonarArgs += " -Dsonar.pullrequest.branch=${env.CHANGE_BRANCH}"
                sonarArgs += " -Dsonar.pullrequest.base=${env.CHANGE_TARGET}"
              } else {
                sonarArgs += " -Dsonar.branch.name=${gitBranch}"
              }

              sh "sonar-scanner ${sonarArgs}"
            }
          }
        }
      }
    }

    stage('Quality Gate') {
      steps {
        timeout(time: 2, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }
  }

  post {
    always {
      cleanWs(deleteDirs: true)
    }
  }
}
