export enum SecurityMonitorSortOption {
  REPO_NAME = 'REPO_NAME',
  DEPENDABOT_ALERTS = 'DEPENDABOT_ALERTS',
  CODE_SCANNING_ALERTS = 'CODE_SCANNING_ALERTS',
  SECRET_SCANNING_ALERTS = 'SECRET_SCANNING_ALERTS'
}

