name: marketplace

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
      - marketcache:/usr/share/nginx/html/market-cache
      - marketbrowser:/usr/share/nginx/html/browser
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - ui
      - app
      - stable
    networks:
      - marketplace-network

  ui:
    image: ghcr.io/axonivy-market/marketplace-ui:${RELEASE_VERSION}
    env_file:
      - .env
    volumes:
      - marketbrowser:/browser_share
    restart: always
    command: sh -c "cp -r /app/dist/browser/* /browser_share && node dist/server/server.mjs"
    expose:
      - "4000"
    networks:
      - marketplace-network

  app:
    image: ghcr.io/axonivy-market/marketplace-app:${RELEASE_VERSION}
    restart: always
    volumes:
      - /home/axonivy/marketplace/data/market-installations.json:/app/data/market-installation.json
      - marketcache:/app/data/market-cache
      - ../logs/app:/app/logs
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - marketplace-network

  stable:
    image: ghcr.io/axonivy-market/marketplace-stable:${RELEASE_VERSION}
    restart: always
    volumes:
      - ../logs/stable:/app/logs
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - marketplace-network

networks:
  marketplace-network:
    external: true

volumes:
  marketcache:
  marketbrowser:
