name: marketplace

services:
  ui:
    container_name: marketplace-ui
    build:
      context: ../../marketplace-ui
      additional_contexts:
        assets: ../../marketplace-build/
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV}
    restart: always
    volumes:
      - ../../marketplace-build/config/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4200:80"
    depends_on:
      - service

  service:
    container_name: marketplace-service
    restart: always
    volumes:
      - /home/axonivy/marketplace/data/market-installations.json:/home/data/market-installation.json
    environment:
      - MONGODB_HOST=${SERVICE_MONGODB_HOST}
      - MONGODB_DATABASE=${SERVICE_MONGODB_DATABASE}
      - MONGODB_USERNAME=${SERVICE_MONGODB_USER}
      - MONGODB_PASSWORD=${SERVICE_MONGODB_PASSWORD}
      - MARKET_GITHUB_MARKET_BRANCH=${MARKET_GITHUB_MARKET_BRANCH}
      - MARKET_GITHUB_TOKEN=${MARKET_GITHUB_TOKEN}
      - MARKET_GITHUB_OAUTH_APP_CLIENT_ID=${MARKET_GITHUB_OAUTH_APP_CLIENT_ID}
      - MARKET_GITHUB_OAUTH_APP_CLIENT_SECRET=${MARKET_GITHUB_OAUTH_APP_CLIENT_SECRET}
      - MARKET_JWT_SECRET_KEY=${MARKET_JWT_SECRET_KEY}
      - MARKET_CORS_ALLOWED_ORIGIN=${MARKET_CORS_ALLOWED_ORIGIN}
    build:
      context: ../../marketplace-service
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION}
    ports:
      - "8080:8080"
