# Used for the local environment
name: marketplace

services:
  ui:
    container_name: marketplace-ui
    build:
      context: ../../marketplace-ui
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV}
    restart: always
    volumes:
      - ../../marketplace-build/config/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - marketcache:/usr/share/nginx/html/market-cache
    ports:
      - "4200:80"
    networks:
      - marketplace-network

  service:
    container_name: marketplace-service
    restart: always
    volumes:
      - /home/axonivy/marketplace/data/market-installations.json:/app/data/market-installation.json
      - marketcache:/app/data/market-cache
      - ../logs:/app/logs
    environment:
      - MONGODB_HOST=${SERVICE_MONGODB_HOST}
      - MONGODB_DATABASE=${SERVICE_MONGODB_DATABASE}
      - MONGODB_USERNAME=${SERVICE_MONGODB_USER}
      - MONGODB_PASSWORD=${SERVICE_MONGODB_PASSWORD}
      - MARKET_GITHUB_MARKET_BRANCH=${MARKET_GITHUB_MARKET_BRANCH}
      - MARKET_GITHUB_TOKEN=${MARKET_GITHUB_TOKEN}
      - MARKET_GITHUB_OAUTH_APP_CLIENT_ID=${MARKET_GITHUB_OAUTH_APP_CLIENT_ID}
      - MARKET_GITHUB_OAUTH_APP_CLIENT_SECRET=${MARKET_GITHUB_OAUTH_APP_CLIENT_SECRET}
      - MARKET_JWT_SECRET_KEY=${MARKET_JWT_SECRET_KEY}
      - MARKET_CORS_ALLOWED_ORIGIN=${MARKET_CORS_ALLOWED_ORIGIN}
      - MARKET_MONGO_LOG_LEVEL=${MARKET_MONGO_LOG_LEVEL}
      - MARKET_LOG_PATH=${MARKET_LOG_PATH}
    build:
      context: ../../marketplace-service
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION}
    ports:
      - "8080:8080"
    networks:
      - marketplace-network

volumes:
  marketcache:

networks:
  marketplace-network:
    external: true