name: marketplace

services:
  hoang-ui:
    container_name: hoang-marketplace-ui
    build:
      context: ../../marketplace-ui
      additional_contexts:
        assets: ../../marketplace-build/
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV}
    restart: always
    image: hoang-marketplace-ui
    volumes:
      - ../../marketplace-build/config/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - hoang-marketcache:/usr/share/nginx/html/market-cache
    ports:
      - "4203:80"
    depends_on:
      - hoang-service
    networks:
      - hoang-marketplace-network

  hoang-service:
    container_name: hoang-marketplace-service
    restart: always
    image: hoang-marketplace-service
    volumes:
      - /home/axonivy/marketplace/data/market-installations.json:/app/data/market-installation.json
      - hoang-marketcache:/app/data/market-cache
    environment:
      - MONGODB_HOST=${SERVICE_MONGODB_HOST}
      - MONGODB_DATABASE=${SERVICE_MONGODB_DATABASE}
      - MONGODB_USERNAME=${SERVICE_MONGODB_USER}
      - MONGODB_PASSWORD=${SERVICE_MONGODB_PASSWORD}
      - MARKET_GITHUB_MARKET_BRANCH=${MARKET_GITHUB_MARKET_BRANCH}
      - MARKET_GITHUB_TOKEN=${MARKET_GITHUB_TOKEN}
      - MARKET_GITHUB_OAUTH_APP_CLIENT_ID=${MARKET_GITHUB_OAUTH_APP_CLIENT_ID}
      - MARKET_GITHUB_OAUTH_APP_CLIENT_SECRET=${MARKET_GITHUB_OAUTH_APP_CLIENT_SECRET}
      - MARKET_JWT_SECRET_KEY=${MARKET_JWT_SECRET_KEY}
      - MARKET_CORS_ALLOWED_ORIGIN=${MARKET_CORS_ALLOWED_ORIGIN}
      - MARKET_MONGO_LOG_LEVEL=${MARKET_MONGO_LOG_LEVEL}
    build:
      context: ../../marketplace-service
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION}
    ports:
      - "8083:8080"
    networks:
      - hoang-marketplace-network

volumes:
  hoang-marketcache:

networks:
  hoang-marketplace-network:
    external: true
