name: marketplace-db

services:
  mongodb:
    container_name: mongodb
    build:
      context: ../config/mongodb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
      - ../config/mongodb/mongod.conf:/etc/mongod.conf

volumes:
  mongodata: