#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE mysuper WITH SUPERUSER CREATEDB CREATEROLE NOLOGIN;
    ALTER USER myuser WITH SUPERUSER;
EOSQL