name: CI Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Executes Tests
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Tests with Maven
      run: mvn clean install
  analysis:
    name: Sonarqube analysis
    needs: build
    runs-on: self-hosted
    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run SonarQube Scanner
        run: |
            mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
                -Dsonar.token=${{ env.SONAR_TOKEN }} \
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        with:
          scanMetadataReportFile: target/sonar/report-task.txt
          args:  -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
