name: DEV Build
run-name: Build and Deploy Marketplace-Service on branch ${{github.ref_name}} by ${{github.actor}}

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    name: Packge project and deploy to tomcat
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

     - name: Prepare deployment directory
       run: mkdir -p deployment && cp target/*.war deployment/

     - name: Copy WAR to Tomcat server
       run: sudo cp deployment/*.war /opt/tomcat/webapps/marketplace-server.war

     - name: Restart Tomcat server
       run: |
          sudo systemctl stop tomcat
          sudo systemctl start tomcat
