name: Market-UI CI Build
run-name: Execute tests for Market-UI on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  pull_request:
    paths:
      - 'marketplace-ui/**'
  push:
    paths:
      - 'marketplace-ui/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: ./marketplace-ui/package-lock.json
      - name: Install Dependencies
        run: |
          cd ./marketplace-ui
          npm install
      - name: Build project
        run: |
          cd ./marketplace-ui
          npm run build
      - name: Execute Tests
        run: |
          cd ./marketplace-ui
          npm run test
