CREATE TABLE IF NOT EXISTS SPRING_SESSION (
  PRIMARY_ID CHAR(36) NOT NULL,
  SESSION_ID CHAR(36) NOT NULL,
  CREATION_TIME BIGINT NOT NULL,
  LAST_ACCESS_TIME BIGINT NOT NULL,
  MAX_INACTIVE_INTERVAL INT NOT NULL,
  EXPIRY_TIME BIGINT NOT NULL,
  PRINCIPAL_NAME VARCHAR(100),
  CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
  SESSION_PRIMARY_ID CHAR(36) NOT NULL,
  ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
  ATTRIBUTE_BYTES BYTEA NOT NULL,
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
    REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.user_entities (
    id            VARCHAR(1024) NOT NULL PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    display_name  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_credentials (
    credential_id                VARCHAR(1024) NOT NULL PRIMARY KEY,
    user_entity_user_id          VARCHAR(1024) NOT NULL REFERENCES public.user_entities (id) ON DELETE CASCADE,
    public_key                   BYTEA NOT NULL,
    signature_count              BIGINT NOT NULL,
    uv_initialized               BOOLEAN NOT NULL,
    backup_eligible              BOOLEAN NOT NULL,
    authenticator_transports      TEXT NOT NULL,
    public_key_credential_type    VARCHAR(64) NOT NULL,
    backup_state                 BOOLEAN NOT NULL,
    attestation_object           BYTEA,
    attestation_client_data_json  BYTEA,
    created                      TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used                    TIMESTAMP WITH TIME ZONE,
    label                        VARCHAR(255)
);
