ALTER TABLE product ADD COLUMN IF NOT EXISTS vendor_logo VARCHAR(255) DEFAULT NULL;

ALTER TABLE product ADD COLUMN IF NOT EXISTS vendor_logo_dark_mode VARCHAR(255) DEFAULT NULL;

ALTER TABLE product ADD COLUMN IF NOT EXISTS internal BOOLEAN DEFAULT NULL;